#!/usr/bin/env python3
"""Make the character map (font ROM contents) for the text mode.

Usage: tools/make_font.py fonts/font8x8_basic.h > mem/font.hex
       tools/make_font.py --pictures fonts/font8x8_basic.h > mem/font.txt

font.hex is plain hex, one byte per line, for $readmemh (XST can't read
comments in it). font.txt is the same data with a picture of each row, for
people.

Takes the 64 characters from space (0x20) to underscore (0x5F): space,
punctuation, digits and the uppercase letters. Each character is 8 rows of
8 pixels, written as 8 hex bytes, one row per line, with the leftmost pixel
in the most significant bit (so the hex reads like the picture):

    30  // ..##....  'A'
    78  // .####...
    CC  // ##..##..

font8x8 stores the leftmost pixel in bit 0; this script reverses the bits.

The source font is font8x8 by Daniel Hepper (public domain), based on the
public domain IBM VGA fonts: https://github.com/dhepper/font8x8
"""
import re
import sys

pictures = sys.argv[1] == '--pictures'
text = open(sys.argv[-1]).read()
glyphs = re.findall(r'\{\s*((?:0x[0-9A-Fa-f]{2},?\s*){8})\}', text)
if len(glyphs) != 128:
    sys.exit('expected 128 glyphs, found %d' % len(glyphs))

def reverse_bits(b):
    return int('{:08b}'.format(b)[::-1], 2)

if pictures:
    print('Character map for projects/textmode: 64 glyphs (0x20 .. 0x5F), 8 rows each.')
    print('Generated by tools/make_font.py from fonts/font8x8_basic.h (public domain).')
for code in range(0x20, 0x60):
    rows = [int(v, 16) for v in re.findall(r'0x[0-9A-Fa-f]{2}', glyphs[code])]
    ch = chr(code)
    for i, r in enumerate(rows):
        r = reverse_bits(r)
        picture = ''.join('#' if r & (0x80 >> c) else '.' for c in range(8))
        label = ("'%s'" % ch if i == 0 else '')
        print('%02X  %s %s' % (r, picture, label) if pictures else '%02X' % r)
