# kronometer5 (2013-04-08): stopwatch on the 7-segment display.
# BTN3 start, BTN2 stop, BTN0 reset. Sources and UCF copied unchanged from
# data/vhdl-2013-rar/vhdl archive 2013 apr 16/kronometer5 (ISE 14.4 project).
TOP  := kronometer5
SRCS := $(wildcard src/*.vhd)
UCF  := pins.ucf
include ../../mk/ise.mk
